Repository RakambdaOrg/OverpoweredMending, pull requests merged in 2023-06, with the labels that each got.

#204 Automatically set version based on git
  build.gradle
  gradle.properties
  gradle/libs.versions.toml
Labels: type: 🧱 enhancement

#207 Support Minecraft 1.20
  fabric/src/main/java/fr/rakambda/overpoweredmending/fabric/wrapper/XpOrbWrapper.java
  forge/src/main/java/fr/rakambda/overpoweredmending/forge/wrapper/XpOrbWrapper.java
  forge/src/main/resources/META-INF/mods.toml
  forge/src/main/resources/pack.mcmeta
  gradle/libs.versions.toml
Labels: type: 🧱 enhancement, modloader: Fabric, modloader: Forge

#215 🔄 synced file(s) with Rakambda/rakambda-github-files
  .github/dependabot.yml
Labels: sync

#216 🔄 synced file(s) with Rakambda/rakambda-github-files
  .github/renovate.json
Labels: sync
